### ISSUE TITLE
Set default editor tabSize for Effekt / Literal Effekt

### ISSUE THREAD

**Issue by jiribenes** [effekt-lang/effekt-vscode#15]
On the _Ξ Effekt Working Group_ meeting, we agreed that the tab size should be 2, but by default, VSCode uses tab size set to 4.
It would be nice to investigate whether we can add a default like:
```
        "editor.tabSize": 2
```
into the extension so that we can ensure nice formatting. :)

However, we should support an override mechanism for the users who _really_ want 4 spaces per soft tab.

**Comment by b-studios** [comment]
Apparently, this can be set per language. But I don't know how to set this _from the extension_:

```
"[effekt]": { "editor.tabSize": 2, "editor.insertSpaces": false, "editor.detectIndentation": false }
```

**Comment by b-studios** [comment]
Turns out, these settings can be added here:

https://github.com/effekt-lang/effekt-vscode/blob/d562223093c3d6289364b5db471260107bd73f8e/package.json#L133-L144
