### ISSUE TITLE
Continue a single-line comment after pressing enter

### ISSUE THREAD

**Issue by jiribenes** [effekt-lang/effekt-vscode#19]
Continue a single-line comment after `<enter>` press by inserting a `//` on the new line.
Use [`onEnterRules`](https://code.visualstudio.com/api/language-extensions/language-configuration-guide#on-enter-rules), and preferably make this configurable.

Related links:
- https://github.com/Microsoft/vscode/issues/11514#issuecomment-244707076
- https://github.com/rust-lang/rust-analyzer/blob/aae54dde8c384acc310455504c9d8909646e0778/editors/code/src/config.ts#L98

As a follow-up, you could try doing the same for `///` (doc comments)

**Comment by b-studios** [comment]
Is this configurable?
